CREATE TABLE funcionario_db(
    id BIGSERIAL PRIMARY KEY,
    cargo VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    data_admissao TIMESTAMP NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    salario DECIMAL(10, 2) NOT NULL
);